// © 2025 Rajith Raja — Velora Systems. All rights reserved. Unauthorised copying or redistribution is prohibited.
// Seed data for Aukštaitija restaurant
export const CATEGORIES = [
  { id: 'starters', name: 'Starters', name_lt: 'Užkandžiai', slug: 'starters', order: 1 },
  { id: 'soups', name: 'Soups', name_lt: 'Sriubos', slug: 'soups', order: 2 },
  { id: 'mains', name: 'Main Courses', name_lt: 'Pagrindiniai patiekalai', slug: 'mains', order: 3 },
  { id: 'desserts', name: 'Desserts', name_lt: 'Desertai', slug: 'desserts', order: 4 },
  { id: 'drinks', name: 'Drinks', name_lt: 'Gėrimai', slug: 'drinks', order: 5 },
];

export const DISHES = [
  {
    id: 'cepelinai',
    name: 'Cepelinai with Smoked Pork',
    name_lt: 'Cepelinai su rūkyta kiauliena',
    description: 'Lithuanian potato dumplings stuffed with seasoned minced pork, served with crispy bacon, sour cream and caramelized onions.',
    description_lt: 'Lietuviški bulviniai cepelinai su mėsos įdaru, traškiais šonkauliukais, grietine ir karamelizuotais svogūnais.',
    price: 14.50,
    category: 'mains',
    dietary_tags: ['non-veg'],
    spice_level: 1,
    available: true,
    prep_time: 25,
    bestseller: true,
    image_url: 'https://images.unsplash.com/photo-1582650365183-fefb14c26acd',
    ingredients: ['Potato', 'Pork', 'Bacon', 'Onion', 'Sour cream', 'Salt', 'Pepper'],
    allergens: ['Gluten', 'Dairy'],
    nutrition: { calories: 580, protein: 28, carbs: 62, fat: 24 },
  },
  {
    id: 'kibinai',
    name: 'Karaim Kibinai',
    name_lt: 'Karaimų kibinai',
    description: 'Traditional Karaim pastries baked golden, filled with lamb, onions and a hint of black pepper.',
    description_lt: 'Tradiciniai karaimų kibinai su aviena, svogūnais ir juodaisiais pipirais.',
    price: 6.50,
    category: 'starters',
    dietary_tags: ['non-veg'],
    spice_level: 1,
    available: true,
    prep_time: 15,
    bestseller: false,
    image_url: 'https://images.unsplash.com/photo-1573070995984-7909aff54aba',
    ingredients: ['Flour', 'Lamb', 'Onion', 'Butter', 'Black pepper'],
    allergens: ['Gluten', 'Dairy'],
    nutrition: { calories: 420, protein: 18, carbs: 38, fat: 22 },
  },
  {
    id: 'saltibarsciai',
    name: 'Šaltibarščiai',
    name_lt: 'Šaltibarščiai',
    description: 'The iconic chilled pink beetroot soup with kefir, dill, cucumber and hard-boiled egg, served with a side of warm potatoes.',
    description_lt: 'Garsioji rožinė šalta burokėlių sriuba su kefyru, krapais, agurkais ir kiaušiniu, su karštomis bulvėmis.',
    price: 7.00,
    category: 'soups',
    dietary_tags: ['veg', 'gluten-free'],
    spice_level: 0,
    available: true,
    prep_time: 10,
    bestseller: true,
    image_url: 'https://images.unsplash.com/photo-1594490393949-7f724f434738',
    ingredients: ['Beetroot', 'Kefir', 'Cucumber', 'Dill', 'Egg', 'Potato'],
    allergens: ['Dairy', 'Eggs'],
    nutrition: { calories: 220, protein: 9, carbs: 28, fat: 8 },
  },
  {
    id: 'salmon',
    name: 'Pan-Seared Baltic Salmon',
    name_lt: 'Keptas Baltijos lašišos filė',
    description: 'Wild Baltic salmon with dill butter, parsnip purée and seasonal greens.',
    description_lt: 'Baltijos lašiša su krapų sviestu, pastarnokų tyre ir sezoninėmis daržovėmis.',
    price: 22.00,
    category: 'mains',
    dietary_tags: ['non-veg', 'gluten-free'],
    spice_level: 0,
    available: true,
    prep_time: 20,
    bestseller: false,
    image_url: 'https://images.unsplash.com/photo-1596591136135-1569bac242bd',
    ingredients: ['Salmon', 'Dill', 'Butter', 'Parsnip', 'Lemon'],
    allergens: ['Fish', 'Dairy'],
    nutrition: { calories: 460, protein: 38, carbs: 12, fat: 28 },
  },
  {
    id: 'beef-tenderloin',
    name: 'Aukštaitija Beef Tenderloin',
    name_lt: 'Aukštaitijos jautienos nugarinė',
    description: 'Aged Lithuanian beef tenderloin with juniper jus, smoked beetroot and forest mushrooms.',
    description_lt: 'Brandinta lietuviška jautienos nugarinė su kadagių padažu, rūkytais burokėliais ir miško grybais.',
    price: 28.00,
    category: 'mains',
    dietary_tags: ['non-veg', 'gluten-free'],
    spice_level: 1,
    available: true,
    prep_time: 30,
    bestseller: true,
    image_url: 'https://images.unsplash.com/photo-1600180786732-6189f0ad253d',
    ingredients: ['Beef tenderloin', 'Juniper', 'Beetroot', 'Mushroom', 'Butter'],
    allergens: ['Dairy'],
    nutrition: { calories: 620, protein: 48, carbs: 8, fat: 42 },
  },
  {
    id: 'rye-bread',
    name: 'Sourdough Rye Plate',
    name_lt: 'Ruginės duonos lėkštė',
    description: 'House-baked sourdough rye with whipped salted butter, hemp seeds and curd cheese.',
    description_lt: 'Namuose kepta rauginta ruginė duona su sūdytu sviestu, kanapių sėklomis ir varške.',
    price: 5.00,
    category: 'starters',
    dietary_tags: ['veg'],
    spice_level: 0,
    available: true,
    prep_time: 5,
    bestseller: false,
    image_url: 'https://images.unsplash.com/photo-1548441975-13ea400a62b0',
    ingredients: ['Rye flour', 'Butter', 'Curd cheese', 'Hemp seeds'],
    allergens: ['Gluten', 'Dairy'],
    nutrition: { calories: 320, protein: 9, carbs: 38, fat: 14 },
  },
  {
    id: 'smoked-duck',
    name: 'Smoked Duck Breast',
    name_lt: 'Rūkyta antienos krūtinėlė',
    description: 'Apple-wood smoked duck breast with lingonberry glaze and roasted root vegetables.',
    description_lt: 'Obels malka rūkyta antienos krūtinėlė su bruknių glazūra ir keptomis daržovėmis.',
    price: 24.00,
    category: 'mains',
    dietary_tags: ['non-veg', 'gluten-free'],
    spice_level: 1,
    available: true,
    prep_time: 25,
    bestseller: false,
    image_url: 'https://images.unsplash.com/photo-1704984678359-b8a4d2a70061',
    ingredients: ['Duck breast', 'Lingonberry', 'Carrot', 'Parsnip', 'Thyme'],
    allergens: [],
    nutrition: { calories: 540, protein: 36, carbs: 18, fat: 32 },
  },
  {
    id: 'mushroom-soup',
    name: 'Wild Forest Mushroom Soup',
    name_lt: 'Miško grybų sriuba',
    description: 'Velvety cream of porcini and chanterelle mushrooms, finished with truffle oil and chives.',
    description_lt: 'Aksominė baravykų ir voveraičių kreminė sriuba su trumų aliejumi.',
    price: 8.50,
    category: 'soups',
    dietary_tags: ['veg'],
    spice_level: 0,
    available: true,
    prep_time: 12,
    bestseller: false,
    image_url: 'https://images.unsplash.com/photo-1606791496080-69a6e309f42c',
    ingredients: ['Porcini', 'Chanterelles', 'Cream', 'Onion', 'Truffle oil'],
    allergens: ['Dairy'],
    nutrition: { calories: 280, protein: 7, carbs: 18, fat: 20 },
  },
  {
    id: 'pork-ribs',
    name: 'Honey-Glazed Pork Ribs',
    name_lt: 'Medumi glazūruoti kiaulienos šonkauliukai',
    description: 'Slow-braised pork ribs glazed with linden honey and dark beer, served with sauerkraut.',
    description_lt: 'Lėtai troškinti kiaulienos šonkauliukai su liepų medumi ir tamsaus alaus glazūra, raugintais kopūstais.',
    price: 19.50,
    category: 'mains',
    dietary_tags: ['non-veg'],
    spice_level: 1,
    available: true,
    prep_time: 35,
    bestseller: true,
    image_url: 'https://images.unsplash.com/photo-1605209971703-73c7ed7c923e',
    ingredients: ['Pork ribs', 'Honey', 'Dark beer', 'Sauerkraut', 'Garlic'],
    allergens: ['Gluten'],
    nutrition: { calories: 720, protein: 42, carbs: 28, fat: 48 },
  },
  {
    id: 'berry-dessert',
    name: 'Forest Berry & Dark Chocolate',
    name_lt: 'Miško uogos ir juodasis šokoladas',
    description: 'Warm dark chocolate fondant with wild forest berries, sour cream sorbet and oat crumble.',
    description_lt: 'Šiltas juodojo šokolado fondantas su miško uogomis, grietinės sorbetu ir avižų trupiniais.',
    price: 9.50,
    category: 'desserts',
    dietary_tags: ['veg'],
    spice_level: 0,
    available: true,
    prep_time: 15,
    bestseller: true,
    image_url: 'https://images.unsplash.com/photo-1637944220604-c5f28faac604',
    ingredients: ['Dark chocolate', 'Forest berries', 'Sour cream', 'Oats', 'Sugar'],
    allergens: ['Dairy', 'Gluten'],
    nutrition: { calories: 480, protein: 8, carbs: 52, fat: 28 },
  },
];
